import Foundation

/// Generates the sing-box configuration for "tunnel mode": a system-wide TUN in FRONT of the VPN client.
///
///   any app ─▶ Waypoint TUN (sing-box) ─┬─▶ direct-phys   (socket pinned to the physical NIC: bypasses the VPN client)
///                                       ├─▶ pool-*        (best of: the VPN client's tunnel + your own servers, per traffic class)
///                                       └─▶ waypoint-race (unknown web traffic → the Swift racer that learns)
///
/// The config is generated by the root daemon from validated data only; nothing user-writable is ever spliced in as raw JSON.
public struct TunnelParams: Equatable {
    public var physicalInterface: String
    public var happInterface: String
    public var racePort: UInt16
    public var directDNS: String
    public var vpnDNS = "1.1.1.1"
    public var ruleSetDir: String
    public var cachePath: String
    public var logPath: String?
    /// false → no TUN, a local mixed (SOCKS/HTTP) inbound instead: used to test the routing logic without root.
    public var tun = true
    public var mixedPort: UInt16 = 7811
    public var stack = "gvisor"
    public var logLevel = "warn"
    /// Send every UDP flow that no rule decided (games, Discord voice…) through the VPN. Also enabled by the policy.
    public var udpViaVPN = false
    /// Clash-compatible local API (live connections, per-server delay). Loopback only, secret required.
    public var apiPort: UInt16 = 9097
    public var apiSecret: String?

    public init(physicalInterface: String, happInterface: String, racePort: UInt16, directDNS: String,
                ruleSetDir: String, cachePath: String, logPath: String? = nil, tun: Bool = true) {
        self.physicalInterface = physicalInterface; self.happInterface = happInterface; self.racePort = racePort
        self.directDNS = directDNS; self.ruleSetDir = ruleSetDir; self.cachePath = cachePath; self.logPath = logPath; self.tun = tun
    }
}

public enum TunnelConfigError: Error, CustomStringConvertible {
    case invalid(String)
    public var description: String { if case .invalid(let s) = self { return s }; return "" }
}

public enum TunnelConfig {
    // MARK: rule-set names (constant structure ⇒ editing rules never needs a restart, only a file reload)

    public static let sourceRuleSetTags: [String] =
        ["manual-block", "manual-vpn", "manual-direct", "app-block", "app-vpn", "app-direct", "svc-block", "svc-direct", "learned-vpn", "starter-direct"]
        + PoolClass.allCases.map { "svc-vpn-\($0.rawValue)" } + PoolClass.allCases.map { "starter-vpn-\($0.rawValue)" }

    // MARK: validation (everything that ends up in a root-run config passes through here)

    public static func isValidInterface(_ s: String) -> Bool {
        s.range(of: #"^(en|utun|bridge|ppp|ipsec)[0-9]{1,3}$"#, options: .regularExpression) != nil
    }
    public static func isValidHostname(_ s: String) -> Bool { isValidToken(s) && s.contains(".") && !s.hasPrefix(".") }
    static func isValidToken(_ s: String) -> Bool {
        !s.isEmpty && s.count <= 253 && s.range(of: #"^[a-z0-9._-]+$"#, options: .regularExpression) != nil
    }

    // MARK: rule-sets (sing-box "source" format, version 5; local files are reloaded automatically on change)

    private struct Bucket {
        var suffix: [String] = [], full: [String] = [], keyword: [String] = [], cidr: [String] = [], process: [String] = []
        var isEmpty: Bool { suffix.isEmpty && full.isEmpty && keyword.isEmpty && cidr.isEmpty && process.isEmpty }
    }

    private static func file(_ b: Bucket) -> Data {
        var rule: [String: Any] = [:]
        if !b.suffix.isEmpty { rule["domain_suffix"] = Array(Set(b.suffix)).sorted() }
        if !b.full.isEmpty { rule["domain"] = Array(Set(b.full)).sorted() }
        if !b.keyword.isEmpty { rule["domain_keyword"] = Array(Set(b.keyword)).sorted() }
        if !b.cidr.isEmpty { rule["ip_cidr"] = Array(Set(b.cidr)).sorted() }
        if !b.process.isEmpty { rule["process_path_regex"] = Array(Set(b.process)).sorted() }
        // An empty rule would match everything; a placeholder that can never match keeps the file valid.
        if rule.isEmpty { rule["domain"] = ["waypoint-placeholder.invalid"] }
        let obj: [String: Any] = ["version": 5, "rules": [rule]]
        return (try? JSONSerialization.data(withJSONObject: obj, options: [.sortedKeys, .prettyPrinted])) ?? Data()
    }

    public static func ruleSets(rules: RuleEngine, policy p: CompiledPolicy, connections: ConnectionPlan = .build([], servers: [])) -> [String: Data] {
        var manual: [Route: Bucket] = [.vpn: Bucket(), .direct: Bucket(), .block: Bucket()]
        for r in rules.manual {
            switch r.kind {
            case .suffix where isValidToken(r.value): manual[r.route]!.suffix.append(r.value)
            case .exact:
                if ipv4Value(r.value) != nil { manual[r.route]!.cidr.append(r.value + "/32") }
                else if isValidToken(r.value) { manual[r.route]!.full.append(r.value) }
            case .keyword where isValidToken(r.value): manual[r.route]!.keyword.append(r.value)
            case .cidr where IPv4CIDR(r.value) != nil: manual[r.route]!.cidr.append(r.value)
            default: break
            }
        }
        var app: [Route: Bucket] = [.vpn: Bucket(), .direct: Bucket(), .block: Bucket()]
        for r in p.appRules where r.kind == .app && AppPath.isValid(r.value) { app[r.route]!.process.append(AppPath.regex(r.value)) }

        var learned = Bucket()
        for e in rules.learnedEntries {
            if e.domain.hasSuffix("/24"), IPv4CIDR(e.domain) != nil { learned.cidr.append(e.domain) }
            else if isValidToken(e.domain) { learned.suffix.append(e.domain) }
        }

        var out: [String: Data] = [
            "manual-block": file(manual[.block]!), "manual-vpn": file(manual[.vpn]!), "manual-direct": file(manual[.direct]!),
            "app-block": file(app[.block]!), "app-vpn": file(app[.vpn]!), "app-direct": file(app[.direct]!),
            "learned-vpn": file(learned),
        ]
        out.merge(connections.files) { _, new in new }
        var sb = Bucket(); sb.suffix = p.svcBlock.filter(isValidToken); out["svc-block"] = file(sb)
        var sd = Bucket(); sd.suffix = p.svcDirect.filter(isValidToken); sd.cidr = p.svcDirectCIDR.filter { IPv4CIDR($0) != nil }; out["svc-direct"] = file(sd)
        var st = Bucket(); st.suffix = p.starterDirect.filter(isValidToken); out["starter-direct"] = file(st)
        for c in PoolClass.allCases {
            var sv = Bucket(); sv.suffix = (p.svcVPN[c] ?? []).filter(isValidToken); sv.cidr = (p.svcVPNCIDR[c] ?? []).filter { IPv4CIDR($0) != nil }
            out["svc-vpn-\(c.rawValue)"] = file(sv)
            var tv = Bucket(); tv.suffix = (p.starterVPN[c] ?? []).filter(isValidToken); tv.cidr = (p.starterVPNCIDR[c] ?? []).filter { IPv4CIDR($0) != nil }
            out["starter-vpn-\(c.rawValue)"] = file(tv)
        }
        return out
    }

    /// Convenience for tests / CLI: policy compiled from default settings for a region.
    public static func ruleSets(rules: RuleEngine, region: Region) -> [String: Data] {
        var s = AppSettings(); s.region = region
        return ruleSets(rules: rules, policy: PolicyCompiler.compile(settings: s, manual: rules.manual))
    }

    // MARK: main config

    public static func generate(_ p: TunnelParams) throws -> Data {
        try generate(p, policy: CompiledPolicy(), servers: [], community: [])
    }

    public static func generate(_ p: TunnelParams, policy: CompiledPolicy,
                                servers: [(tag: String, server: ParsedServer)], community: [CommunityList],
                                connectionServers: [String] = []) throws -> Data {
        guard isValidInterface(p.physicalInterface) else { throw TunnelConfigError.invalid("bad physical interface \(p.physicalInterface)") }
        guard isValidInterface(p.happInterface) else { throw TunnelConfigError.invalid("bad VPN interface \(p.happInterface)") }
        guard ipv4Value(p.directDNS) != nil, ipv4Value(p.vpnDNS) != nil else { throw TunnelConfigError.invalid("bad DNS address") }
        guard p.racePort > 1024, p.apiPort > 1024 else { throw TunnelConfigError.invalid("bad port") }
        guard ["system", "gvisor", "mixed"].contains(p.stack) else { throw TunnelConfigError.invalid("bad stack") }
        guard ["trace", "debug", "info", "warn", "error"].contains(p.logLevel) else { throw TunnelConfigError.invalid("bad log level") }
        if let s = p.apiSecret { guard s.range(of: #"^[0-9a-f]{16,64}$"#, options: .regularExpression) != nil else { throw TunnelConfigError.invalid("bad api secret") } }
        for c in community { guard CommunityList.all.contains(c) else { throw TunnelConfigError.invalid("unknown community list") } }

        let mode = policy.finalMode
        let hasPool = !servers.isEmpty
        func pool(_ c: PoolClass) -> String { hasPool ? "pool-\(c.rawValue)" : "via-happ" }

        func local(_ tag: String, format: String, file: String) -> [String: Any] {
            ["type": "local", "tag": tag, "format": format, "path": "\(p.ruleSetDir)/\(file)"]
        }
        func route(_ tag: String, _ outbound: String) -> [String: Any] { ["rule_set": [tag], "action": "route", "outbound": outbound] }

        // ---- rule-sets
        let serverTags = Set(servers.map(\.tag))
        let connServers = connectionServers.filter { $0.range(of: #"^srv-[0-9]{1,4}$"#, options: .regularExpression) != nil }
        var connTags = ConnectionPlan.fixedTags
        for t in ConnectionRule.Tier.allCases { connTags += connServers.map { ConnectionPlan.setName(t, $0) } }
        var ruleSetDefs: [[String: Any]] = (sourceRuleSetTags + connTags).map { local($0, format: "source", file: "\($0).json") }
        ruleSetDefs += community.map { local($0.id, format: "binary", file: $0.file) }

        // ---- inbounds
        var inbounds: [[String: Any]]
        if p.tun {
            inbounds = [[
                "type": "tun", "tag": "tun-in", "address": ["172.19.0.1/30"],
                "auto_route": true, "strict_route": false, "stack": p.stack, "mtu": 1500,
                // Link-local, multicast and CGNAT (Tailscale) never enter the tunnel. Private LAN ranges deliberately DO:
                // the router is usually the DNS server, and its queries must be hijacked to get FakeIP. LAN traffic itself
                // is sent to direct-phys by the `ip_is_private` rule.
                "route_exclude_address": ["169.254.0.0/16", "224.0.0.0/4", "100.64.0.0/10"],
            ]]
        } else {
            inbounds = [["type": "mixed", "tag": "mixed-in", "listen": "127.0.0.1", "listen_port": Int(p.mixedPort)]]
        }

        /// Per-connection rules of one tier: block / direct / VPN client / best VPN / an exact server
        /// (a server shed by the pre-flight falls back to the best VPN instead of breaking the config).
        func connection(_ tier: ConnectionRule.Tier) -> [[String: Any]] {
            var out: [[String: Any]] = [["rule_set": [ConnectionPlan.setName(tier, "block")], "action": "reject"],
                                        route(ConnectionPlan.setName(tier, "direct"), "direct-phys"),
                                        route(ConnectionPlan.setName(tier, "client"), "via-happ")]
            for tag in connServers { out.append(route(ConnectionPlan.setName(tier, tag), serverTags.contains(tag) ? tag : pool(.general))) }
            out.append(route(ConnectionPlan.setName(tier, "vpn"), pool(.general)))
            return out
        }

        // ---- route rules, most explicit first
        var rules: [[String: Any]] = [["action": "sniff", "sniffer": ["tls", "http", "quic", "dns"]]]
        if p.tun { rules.append(["protocol": "dns", "action": "hijack-dns"]) }
        rules += [
            ["ip_is_private": true, "action": "route", "outbound": "direct-phys"],
        ]
        rules += connection(.pair)                              // «this app to this site» is the most explicit choice there is
        rules += [
            ["rule_set": ["manual-block"], "action": "reject"],
            ["rule_set": ["app-block"], "action": "reject"],
            route("app-direct", "direct-phys"),                 // an explicit choice for an application beats domain rules
            route("app-vpn", pool(.general)),
        ]
        rules += connection(.app)
        rules += [
            route("manual-direct", "direct-phys"),
            route("manual-vpn", pool(.general)),
        ]
        rules += connection(.site)
        rules += [
            ["rule_set": ["svc-block"], "action": "reject"],
            route("svc-direct", "direct-phys"),
        ]
        for c in PoolClass.allCases { rules.append(route("svc-vpn-\(c.rawValue)", pool(c))) }
        // Services that only work from a local address stay direct even if something below (learning!) says otherwise.
        for l in community where l.role == .directStrict { rules.append(route(l.id, "direct-phys")) }
        rules.append(route("learned-vpn", pool(.general)))
        for c in PoolClass.allCases { rules.append(route("starter-vpn-\(c.rawValue)", pool(c))) }
        for l in community { if case .vpn(let c) = l.role { rules.append(route(l.id, pool(c))) } }
        rules.append(route("starter-direct", "direct-phys"))
        for l in community where l.role == .direct { rules.append(route(l.id, "direct-phys")) }

        let udpVPN = p.udpViaVPN || policy.udpViaVPN
        switch mode {
        case .allVPN:
            break                                                // everything undecided falls through to `final` = the VPN
        case .savings:
            if udpVPN { rules.append(["network": "udp", "action": "route", "outbound": pool(.chat)]) }
        case .auto:
            // QUIC to anything undecided: refuse, so browsers fall back to TCP immediately — and TCP is what the racer learns from.
            rules.append(["network": "udp", "port": 443, "action": "reject"])
            if udpVPN { rules.append(["network": "udp", "action": "route", "outbound": pool(.chat)]) }
            // Only what sing-box positively identified as TLS/HTTP may be raced: the racer validates replies as TLS/HTTP, so
            // anything else on 80/443 (Telegram MTProto, custom protocols) would be rejected on *both* paths.
            rules.append(["network": "tcp", "port": [80, 443, 8080, 8443], "protocol": ["tls", "http"], "action": "route", "outbound": "waypoint-race"])
        }
        let finalOutbound = mode == .allVPN ? pool(.general) : "direct-phys"

        // ---- outbounds
        var outbounds: [[String: Any]] = [
            ["type": "direct", "tag": "direct-phys", "bind_interface": p.physicalInterface, "domain_resolver": "dns-direct"],
            ["type": "direct", "tag": "via-happ", "bind_interface": p.happInterface, "domain_resolver": "dns-vpn"],
            // Loopback must be bound to lo0 explicitly, otherwise `default_interface` would push it out of the physical NIC.
            ["type": "socks", "tag": "waypoint-race", "server": "127.0.0.1", "server_port": Int(p.racePort), "version": "5", "bind_interface": "lo0"],
        ]
        for s in servers {
            var o = s.server.outbound; o["tag"] = s.tag
            // A dead address must fail in seconds, not minutes, so the pool can pick another server (not for QUIC-based types).
            if let t = o["type"] as? String, ["vless", "trojan", "shadowsocks", "vmess", "http"].contains(t) { o["connect_timeout"] = "8s" }
            outbounds.append(o)
        }
        if hasPool {
            for c in PoolClass.allCases {
                outbounds.append(["type": "urltest", "tag": "pool-\(c.rawValue)", "outbounds": ["via-happ"] + servers.map(\.tag),
                                  "url": c.testURL, "interval": "2m", "tolerance": 100, "idle_timeout": "30m",
                                  // when the chosen server changes, connections stuck on the old one are reset so apps reconnect at once
                                  "interrupt_exist_connections": true])
            }
        }

        var log: [String: Any] = ["level": p.logLevel, "timestamp": true]
        if let l = p.logPath { log["output"] = l }
        var experimental: [String: Any] = ["cache_file": ["enabled": true, "path": p.cachePath, "store_fakeip": true]]
        if let secret = p.apiSecret { experimental["clash_api"] = ["external_controller": "127.0.0.1:\(p.apiPort)", "secret": secret] }

        let config: [String: Any] = [
            "log": log,
            "experimental": experimental,
            "dns": [
                "servers": [
                    ["type": "udp", "tag": "dns-direct", "server": p.directDNS, "bind_interface": p.physicalInterface],
                    ["type": "https", "tag": "dns-vpn", "server": p.vpnDNS, "bind_interface": p.happInterface],
                    ["type": "fakeip", "tag": "dns-fake", "inet4_range": "198.19.0.0/16"],
                ],
                "rules": [
                    ["domain_suffix": ["local", "lan", "home.arpa"], "action": "route", "server": "dns-direct"],
                    // Every name apps look up gets a fake address that maps back to the *name* (for resolvers that reach the TUN).
                    ["query_type": ["A", "AAAA"], "action": "route", "server": "dns-fake"],
                ],
                "final": mode == .allVPN ? "dns-vpn" : "dns-direct",
                "strategy": "ipv4_only",
            ],
            "inbounds": inbounds,
            "outbounds": outbounds,
            "route": [
                "rule_set": ruleSetDefs,
                "rules": rules,
                "final": finalOutbound,
                "find_process": true,                            // needed for per-application rules and the live connections view
                "default_interface": p.physicalInterface,        // your own servers dial out through the real NIC, never into the TUN
                "default_domain_resolver": "dns-direct",
            ],
        ]
        return try JSONSerialization.data(withJSONObject: config, options: [.sortedKeys, .prettyPrinted])
    }
}
